// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxkhrHyl-sPEgs306toebTRlrjemvccVM',
    appId: '1:597228862194:web:c21eb89065787a4b246e6b',
    messagingSenderId: '597228862194',
    projectId: 'trackerapp-bd511',
    authDomain: 'trackerapp-bd511.firebaseapp.com',
    storageBucket: 'trackerapp-bd511.appspot.com',
    measurementId: 'G-G82M5R8VY6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ3DJlBLGqqr0-SfbVZL3Kx7T4c4NKD6s',
    appId: '1:597228862194:android:22dc05871b9af39d246e6b',
    messagingSenderId: '597228862194',
    projectId: 'trackerapp-bd511',
    storageBucket: 'trackerapp-bd511.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD30ILlU1whsRUmJOpe_5lf1QleJSezooE',
    appId: '1:597228862194:ios:60895f9ea1840fa4246e6b',
    messagingSenderId: '597228862194',
    projectId: 'trackerapp-bd511',
    storageBucket: 'trackerapp-bd511.appspot.com',
    iosClientId: '597228862194-oe28a4b5phkdmp8e7feivlvdur3un8tg.apps.googleusercontent.com',
    iosBundleId: 'com.example.keepBooks',
  );
}
